SELECT LENGTH('skyfall');

SELECT first_name, LENGTH(first_name)
FROM employee_demographics
ORDER BY 2;


SELECT UPPER('sky');
SELECT LOWER('SKY');
SELECT TRIM(' SKY ' );
SELECT RTRIM('SKY '); -- SPACE TO THE RIGHT;
SELECT LTRIM(' SKY'); -- SPACE TO THE LEFT
